### ISSUE TITLE
Sending messages to kafka reliably

### ISSUE THREAD

**Issue by yan-khonski-it** [sohangp/outbox-pattern#1]
Hi

Problem, how do I know that messages will come to kafka? Even if **debezium-connect** can be temporary down.

Example
I have running all services. I create students in student app
```
HTTP POST http://localhost:8080/students/~/enroll

{ 
    "name": "Yan-1",
    "email": "mclark@gmail.com",
    "address": "Toronto, ON"
}
```
The message comes to kafka
```
{"schema":null,"payload":"{\"studentId\":4,\"name\":\"Yan-1\",\"email\":\"mclark@gmail.com\",\"address\":\"Toronto, ON\"}"}
```

Now, I stopped debezium connect. `docker-compose stop debezium-connect`.
Imagine a real world situation when some containers can go down.

Then I create a user.
```
HTTP POST http://localhost:8080/students/~/enroll

{ 
    "name": "Yan-2 ebezium is down",
    "email": "mclark@gmail.com",
    "address": "Toronto, ON"
}
```
The student record is created in the database. However, there is not kafka message.

**Comment by sohangp** [comment]
Hello, 

I agree with you in the real world containers can go down and they come up. That's the caveat here, the containers do come back up an when they come back up they must pick up from where they left off (this pattern follows [Eventual Consistency](https://microservices.io/patterns/data/event-driven-architecture.html)).

In the above example (as you mentioned), I take down the with the command ```docker-compose stop debezium-connect```. Then I create a new student with the command: 

_New Student Created:_ 
```bash
curl  POST 'http://localhost:8080/students/~/enroll' \
--header 'Content-Type: application/json' \
--data-raw '{ 
    "name": "Test Me",
    "email": "tMe@gmail.com",
    "address": "Toronto, ON"
}'
```

As you mentioned I don't see the message being published in Kafka.
But when I start the connector back on with the command  ```docker-compose start debezium-connect```. I see the message come through like it never missed it (with the delay between it being started again).

```bash
{"schema":null,"payload":"{\"studentId\":5,\"name\":\"Test Me\",\"email\":\"tMe@gmail.com\",\"address\":\"Toronto, ON\"}"}
``` 

I would recommend you always run the Debezium connect as a cluster to reduce the failure, but when the entire cluster fails and comes back on, it picks up where it stopped.
